### PR TITLE
null safety

### PR DESCRIPTION
**Pull request by matejkramny**
Support for null safety.

There's a package linking to git, since it also needed migration

### CODE REVIEW

**Comment by trapeye** [comment]
how to use this null safety?

**Comment by farellsujanto** [comment]
@matejkramny hey can you publish your own PR to dart pub? I dont think they still maintain this one and a lot of people including me needs an esc package so badly (no alternative). Thanks!

**Comment by tungpham6195** [comment]
hi guys, can you guys merge it in? @andrey-ushakov , @ccfiel , @WashingtonlGarcia , @en237

**Comment by matejkramny** [comment]
@farellsujanto @tungpham6195 hard forked to a new package, now maintained by Castaway labs

https://pub.dev/packages/escpos https://github.com/CastawayLabs/dart-escpos

**Pull request closed without merging**
