### PR TITLE
cash drawer function added

### PR DESCRIPTION
**Pull request by mjafartp**
Added function to open cash drawer.

### CODE REVIEW

**Comment by ccfiel** [comment]
why this is not merge? :) @andrey-ushakov

**Comment by andrey-ushakov** [comment]
Hi @ccfiel,

Thank you for your interest!
Unfortunately, I have very little time these days... Probably I will try to check some issues and this PR this weekend.

**Comment by ccfiel** [comment]
@andrey-ushakov Thanks for this package! :)

**Comment by ccfiel** [comment]
@mjafartp can you update this? There are conflicts :)

**Comment by ccfiel** [comment]
@andrey-ushakov if this is updated would you accept the PR? :) or do you have any suggestion

**Comment by andrey-ushakov** [comment]
Hi @mjafartp, @mjafartp !

I will definitely look into it, a bit later :)

Actually, yesterday I've split the library into three packages (`esc_pos_printer`, `esc_pos_bluetooth` and `esc_pos_utils`), that's why there are conflicts now.

I'm trying to improve the ticket generation code because it seems that some printers implement the ESC/POS commands in a slightly different way which makes, for example, all the printing output in bold or underlined or reversed...

So firstly I'm trying to find a way how to support as many printers as possible and after that new features including that one will be added :)

**Comment by ccfiel** [comment]
@andrey-ushakov thanks!

**Comment by andrey-ushakov** [comment]
I've just added the cash drawer command as suggested in this PR.
Unfortunately, I have no drawer to test. May I ask you to test it, please? :)

**Comment by ccfiel** [comment]
@andrey-ushakov I will try today. I will give feedback.

**Comment by ccfiel** [comment]
@andrey-ushakov its working :) We can close this issue. Thanks!

**Comment by andrey-ushakov** [comment]
Awesome!

**Pull request closed without merging**
